<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-windows;net48</TargetFrameworks>
    <RootNamespace>CredentialManagement</RootNamespace>
    <AssemblyName>CredentialManagement</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net10.0-windows'">6.1</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1507;CA1510;CA1513;CA1707;CA1838;CA2208</NoWarn>
  </PropertyGroup>
</Project>
